apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/infrastructure
- cilium.yaml
- external-dns-secret.yaml
- cert-manager-secret.yaml
- cloudflared.yaml
- cloudflared-credentials-secret.yaml
