apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
stringData:
    token: ENC[AES256_GCM,data:moa+W063oWMx9C7Xsj/QnuKgRaqDZoXsk9jk5mqdO9p1+IrMQ9QfQcBWrbFUIvQ/j5r6h1o=,iv:tvQ2JVbMPIEI4eMJt6MxtUW96PkCoK40dcg0oA/SIH4=,tag:ReN2IMZ373zy7TmjTPt4zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb1ZPMWNJbFJtSWFFZTVz
            aWlPdGwvbmxKQUo5UE9mUkU1b3pEeGJEdHo4CnpHaEVmV2JCK2xkcWFHNHd4dldr
            aTBPUW5xVjQ5cUtRaktrTGlORnNIYkEKLS0tIHhtYk5paklqanN6K1Z6TSt4MmVK
            bUFuOUdSQ0c3dzZWUCtOcWVqbE1sOE0Krwfzd8Rp2h+3EKz4rd/92XtjyQXfXr6O
            XUYbfNeq0soN/V5sx9lB4vFydkmuXNFB1hKvMQY7kD+/H9ul3a9YJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age100029hv4crfdtd2yu8fxvfajjfstjg83x8v6dn5v7preg4j8uq7svyvt6n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T21:28:23Z"
    mac: ENC[AES256_GCM,data:CaV0OgYnn5WEdlABwz7HYYPccZeKDpYrNO1If8fXEdVCLZQVVBO0G5D5uKY6vvjGN+Aw9QBWruluKLg4OzYZN21dZyWYuNnwPngX2Fl0DjOY10NwtdINuTA+ZxLVJj2LKjMr7CgRKNnJuUQvdOYXw2sIIX5AU2yK/mVpLJGmhII=,iv:/t6TOues7EyogFAXaappYXi+sHhBevh8hmpigzJXbjw=,tag:pF0C3yB2zs7rN/oOlPa/6g==,type:str]
    version: 3.13.2
