apiVersion: ENC[AES256_GCM,data:6UI=,iv:TyPuNXaaq8BvoPP6LHo+ByZBtbcZXqu8er/Thqg7fqw=,tag:Vrh/CPBA4Ry8ECvGAF3RGw==,type:str]
kind: ENC[AES256_GCM,data:KQcwqGZt,iv:nEmIP1oEZPzUv6NURrf5h6Hpgbjxug8J5mP92EsrJ+c=,tag:E1P0iavZ8QhC6PKRShoEbQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GAWZ/mR/dY3ZPvvIYXT+TCCwbks=,iv:b4MQVI/TZCRN+vEjt0zraoki3iqylDAi+o8Xs9y39kI=,tag:8bNzvX06PszEoNKBV+YTBg==,type:str]
    namespace: ENC[AES256_GCM,data:Skxt5l+8QYNpIvNv,iv:akSdHUWayHSye+lsz2XOXzKNBPMrasGjOLPo9bGxzy0=,tag:ypFbe36NzlP+JD0RDnKmUA==,type:str]
stringData:
    token: ENC[AES256_GCM,data:YnVnnZKd5s9nJScn8d8n1zR3+/jaMkX9skHsLW4v62XfrLhC1QcHUQKj69pSRA6PlvPRZio=,iv:JKGU+PT54lIMXM08c4MeWEIGDZRfN6JsE/Q4XfNboTE=,tag:JIgWfnYoxobOq3Zfey7tUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMEhKRTZseTQrZTlRMjlk
            SVBNQTBoNnQ4dVF6WEo1bkRaL1hpditLeWdZCkFKT3Y4WmpvWVhHb3FyQmFkUktJ
            bmJ5T0pmOWJFM3V1R0lrNmp3MStsMG8KLS0tIG9XVk1qZmV4N2pvZjhYMkNFVWYv
            dlE3Y1REZ1IrZEJPYSt6d1lSTllRTVkKHvXgJtv0DZofPfYbb3eHoKcYaJ1ujm4w
            LEs+W99yG42QghTaG8G44PS6c/HgCp92IUzTJg6E4yVC3Iz81I//vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age100029hv4crfdtd2yu8fxvfajjfstjg83x8v6dn5v7preg4j8uq7svyvt6n
    lastmodified: "2026-07-01T18:35:21Z"
    mac: ENC[AES256_GCM,data:ZwzknxdCpKwVIKt6nhPtEdGLd2MkaCkjC9KH7q9AqCP5OQGtb5Du159lL2zIeVPwhgAPglleuhRBhsRbPqHYagtCWKtMo4yf7JYSGh24ntPPKgGJOynrhARuWtXxrXM+bcBgIsj17qp909teTZxFdifeTZ8GygBv5/z8gigNQLQ=,iv:CDzAgaqfmR6nY3xpMlunZsUBKc2PVv2xgyfyBaOfkpc=,tag:aB2ba1Bd+cAHNEyNvnkvKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
